$ Mission configuration for Apf11(19821) FwRev 052321:
$ AscentTimeOut(540) [min]
$ AtDialCmd(AT+CBST=71,0,1;DT00881600005477) [primary]
$ AltDialCmd(ATDT0012066163256) [alternate]
$ BuoyancyNudge(10) [count]
$ CompensatorHyperRetraction(0) [count]
$ ConnectTimeOut(60) [sec]
$ CpActivationP(985) [dbar]
$ DeepProfileDescentTime(240) [min]
$ DeepProfilePistonPos(10) [count]
$ DeepProfilePressure(2020) [dbar]
$ DownTime(14400) [min]
$ DuraRefWarmUpHrs(255)
$ DuraInit(-1) [Enable<0, Disable=0, Enable&Init>0]
$ FatFsEnable(1)
$ FlbbMode(1)
$ FloatId(19821)
$ FullExtension(231) [count]
$ FullRetraction(9) [count]
$ InitialBuoyancyNudge(22) [count]
$ IsusInit(-1) [Enable<0, Disable=0, Enable&Init>0]
$ MaxAirBladder(154) [count]
$ MaxLogKb(40) [KByte]
$ MissionPrelude(360) [min]
$ OkVacuum(237) [count]
$ PActivationPistonPosition(16) [count]
$ ParkDescentTime(240) [min]
$ ParkPistonPos(66) [count]
$ ParkPressure(1000) [dbar]
$ PnPCycleLen(1)
$ TelemetryRetry(15) [min]
$ TimeOfDay(DISABLED) [min]
$ UpTime(660) [min]
$ ZModemTimeOut(80) [sec]
$ Verbosity(2)
$ DebugBits(0x0002)
$
# GPS fix obtained in 12 seconds.
#          lon      lat mm/dd/yyyy hhmmss nsat
Fix:  -86.9231  26.7123 09/22/2021 182340    9
IridiumGeo: <x,y,z>:   304km -5688km  2852km IrSysTime: 0x99fd3461
IridiumFix: <lon,lat>:  -86.941  26.751 IrEpoch: 1632333960sec 09/22/2021 18:06:00
Apf11FwRev=052321
ActiveBallastAdjustments=0
AirBladderPressure=155
AirPumpAmps=25
AirPumpVolts=218
BuoyancyPumpOnTime=1204
BuoyancyPumpAmps=0
BuoyancyPumpVolts=0
ConnectionAttempts=1
Connections=1
CurrentPistonPosition=231
Coulombs=1.6kC
CoulombsDescent=0.0kC
CoulombsPark=0.0kC
CoulombsPrfDescent=0.0kC
CoulombsProfile=0.0kC
CoulombsTelemetry=1.9kC
DeepProfilePistonPosition=10
DuraPowerCycleCounter=0
DuraWakeCurrent=0.0mA
DuraWakePower=0.0mW
DuraWakeVolts=0.0V
FlbbAmps=0
FlbbVolts=0
FlbbStatus=0x00
GpsFixTime=12
HumidityAd12Park=0 (-23.8%)
HumidityAd12Pneumatic=0 (-23.8%)
HumidityAd12PneumaticRef=0 (-23.8%)
FloatId=19821
IsusPowerCycleCounter=0
IsusWakeCurrent=0.0mA
IsusWakePower=0.0mW
IsusWakeVolts=0.0V
MuxerTemperature=0.00C
MuxerHumidity=0.0%
MuxerWakeCurrent=0.0mA
MuxerWakePower=0.0mW
MuxerWakeVolts=0.0V
ParkDescentPCnt=0
ParkPistonPosition=66
ParkObs={ 0.0dbar, 0.000C, 0.0000PSU / nan / 0.000C 0.000 0.000 / 0, 0, 0}
ProfileId=000
ObsIndex=0
QuiescentAmps=0
QuiescentVolts=0
RtcSkew=-1
Sbe41cpAmps=0
Sbe41cpVolts=0
Sbe41cpStatus=0x00000000
SleepSec=15387
StandbySec=2596518
status=0x00000000
SurfaceObs={ -0.1dbar, nan, nan / nan / 29.693C 28.787 7.648 / 56, 133, 528}
SurfacePistonPosition=0
SurfacePressure=0.00
TimeStartDescent=0                  
TimeStartPark=0                     
TimeStartProfileDescent=0           
TimeStartProfile=0                  
TimeStopProfile=0                   
TimeStartTelemetry=1632334927       Sep 22 2021 18:22:07
Vacuum=214
WakeCycles=432
WakeSec=6234

<EOT>
