# GPS fix obtained in 24 seconds.
#          lon      lat mm/dd/yyyy hhmmss nsat
Fix:  -88.5812  25.8459 06/06/2023 041500    9
NpfFwRev=BGCi_SUNA_PH_ICE 190520
ActiveBallastAdjustments=0
AirBladderPressure=137
AirPumpAmps=283
AirPumpVolts=2308
BatteryCounts=624502
BuoyancyPumpOnTime=1427
BuoyancyPumpAmps=0
BuoyancyPumpVolts=0
CurrentBuoyancyPosition=880
DeepProfileBuoyancyPosition=151
FlashErrorsCorrectable=0
FlashErrorsUncorrectable=0
FloatId=1469
GpsFixTime=24
IceEvasionRecord=0x00
IceMLMedianT=nanC
IceMLSample=0
IsusPowerCycleCounter=0
McomsAmps=0
McomsVolts=0
ParkDescentPCnt=0
ParkBuoyancyPosition=304
ParkObs={  0.0dbar,0.000C,0.0000PSU / 0.000us,0.000000V / 0,0,0 / 0.000000V}
pHBaseAmps=0
pHBatteryInVolts=0.00
pHBatteryOutVolts=0.00
pHCounterVolts=0.000000
pHCounterAmps=0
ProfileId=000
ObsIndex=0
QuiescentAmps=0
QuiescentVolts=0
RtcSkew=-1
Sbe41cpAmps=0
Sbe41cpVolts=0
Sbe41cpHumidity=0.00
Sbe41cpHumidityTemp=0.00
Sbe41cpStatus=0x00000000
Sbe63Amps=0
Sbe63Volts=0
status=0x00000000
SurfaceBuoyancyPosition=0
SurfacePressure=0.00
TimeStartDescent=0                  
TimeStartPark=0                     
TimeStartProfileDescent=0           
TimeStartProfile=0                  
TimeStopProfile=0                   
TimeStartTelemetry=1686024838       Jun 06 2023 04:13:58
Vacuum=92

<EOT>
