$ Mission configuration for Apf11(19073) FwRev 052321:
$ AscentTimeOut(540) [min]
$ AtDialCmd(AT+CBST=71,0,1;DT00881600005477) [primary]
$ AltDialCmd(ATDT0012066163256) [alternate]
$ BuoyancyNudge(10) [count]
$ CompensatorHyperRetraction(0) [count]
$ ConnectTimeOut(60) [sec]
$ CpActivationP(985) [dbar]
$ DeepProfileDescentTime(240) [min]
$ DeepProfilePistonPos(10) [count]
$ DeepProfilePressure(2020) [dbar]
$ DownTime(14400) [min]
$ DuraRefWarmUpHrs(255)
$ DuraInit(-1) [Enable<0, Disable=0, Enable&Init>0]
$ FatFsEnable(1)
$ FlbbMode(1)
$ FloatId(19073)
$ FullExtension(231) [count]
$ FullRetraction(9) [count]
$ InitialBuoyancyNudge(22) [count]
$ IsusInit(-1) [Enable<0, Disable=0, Enable&Init>0]
$ MaxAirBladder(153) [count]
$ MaxLogKb(40) [KByte]
$ MissionPrelude(360) [min]
$ OkVacuum(236) [count]
$ PActivationPistonPosition(16) [count]
$ ParkDescentTime(240) [min]
$ ParkPistonPos(66) [count]
$ ParkPressure(1000) [dbar]
$ PnPCycleLen(1)
$ TelemetryRetry(15) [min]
$ TimeOfDay(DISABLED) [min]
$ UpTime(660) [min]
$ ZModemTimeOut(80) [sec]
$ Verbosity(2)
$ DebugBits(0x0002)
$
# GPS fix obtained in 27 seconds.
#          lon      lat mm/dd/yyyy hhmmss nsat
Fix:  -93.3941  24.8815 10/05/2021 063800    9
IridiumGeo: <x,y,z>:  -336km -5776km  2668km IrSysTime: 0x9ab498a1
IridiumFix: <lon,lat>:  -93.329  24.902 IrEpoch: 1633415648sec 10/05/2021 06:34:08
Apf11FwRev=052321
ActiveBallastAdjustments=0
AirBladderPressure=155
AirPumpAmps=25
AirPumpVolts=212
BuoyancyPumpOnTime=1179
BuoyancyPumpAmps=0
BuoyancyPumpVolts=0
ConnectionAttempts=1
Connections=1
CurrentPistonPosition=231
Coulombs=1.5kC
CoulombsDescent=0.0kC
CoulombsPark=0.0kC
CoulombsPrfDescent=0.0kC
CoulombsProfile=0.0kC
CoulombsTelemetry=1.9kC
DeepProfilePistonPosition=10
DuraPowerCycleCounter=0
DuraWakeCurrent=0.0mA
DuraWakePower=0.0mW
DuraWakeVolts=0.0V
FlbbAmps=0
FlbbVolts=0
FlbbStatus=0x00
GpsFixTime=27
HumidityAd12Park=0 (-23.8%)
HumidityAd12Pneumatic=0 (-23.8%)
HumidityAd12PneumaticRef=0 (-23.8%)
FloatId=19073
IsusPowerCycleCounter=0
IsusWakeCurrent=0.0mA
IsusWakePower=0.0mW
IsusWakeVolts=0.0V
MuxerTemperature=0.00C
MuxerHumidity=0.0%
MuxerWakeCurrent=0.0mA
MuxerWakePower=0.0mW
MuxerWakeVolts=0.0V
ParkDescentPCnt=0
ParkPistonPosition=66
ParkObs={ 0.0dbar, 0.000C, 0.0000PSU / nan / 0.000C 0.000 0.000 / 0, 0, 0}
ProfileId=000
ObsIndex=0
QuiescentAmps=0
QuiescentVolts=0
RtcSkew=1
Sbe41cpAmps=0
Sbe41cpVolts=0
Sbe41cpStatus=0x00000000
SleepSec=15467
StandbySec=3654647
status=0x00000000
SurfaceObs={ -0.2dbar, nan, nan / nan / 26.876C 30.439 8.047 / 61, 129, 527}
SurfacePistonPosition=0
SurfacePressure=0.00
TimeStartDescent=0                  
TimeStartPark=0                     
TimeStartProfileDescent=0           
TimeStartProfile=0                  
TimeStopProfile=0                   
TimeStartTelemetry=1633415798       Oct 05 2021 06:36:38
Vacuum=219
WakeCycles=601
WakeSec=6401

<EOT>
